### ISSUE TITLE
[enhancement] Give feedback via `wash ctl link query`/washboard when link definitions are malformed

### ISSUE THREAD

**Issue by alsuren** [wasmCloud/capability-providers#111]
I'm not sure what the correct solution to this is, but I will tell you a story anyway.

I was trying to set up a docker-compose environment so that I had a minimal reproduction environment for reporting any bugs I found, and to verify the fix for a bug reported earlier.

i started with:
```
wash ctl link put \
    MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5 \
    VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M \
    wasmcloud:httpserver \
    PORT=8081
```
but the http server listens on 127.0.0.1 by default, and docker's port-forwarding doesn't forward to 127.0.0.1, so I didn't get anywhere with that.

I then read the source code for the provider to see what parameters it accepted. I saw `address`, and tried:

```
wash ctl link put \
    MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5 \
    VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M \
    wasmcloud:httpserver \
    ADDRESS=0.0.0.1 \
    PORT=8081
```

This caused a log in the http capability provider, but I did not spot it in the docker-compose logs until sometime later. By the time I switched to the docker-compose logs, the error had been buried in `Handling host heartbeat` spam, and I missed it. I ended up fixing the problem by reading the source for `impl From<String> for SocketAddress` or something, I think.
```
wasmcloud-a_1  |  ERROR wasmbus_rpc::provider > put_link MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5 failed: provider initialization or put-link: invalid parameter: invalid address: 0.0.0.0
```

I was looking in `wash ctl link query` and `wash ctl get inventory ...` and washboard, and didn't see anything reported in those places.

<details>
<summary>In case anyone is looking for a minimal docker-compose environment: once I figured out what was happening and fixed my error, I ended up with a docker-compose.yml like this:</summary>

```yaml
version: "3"
services:
  nats:
    image: nats:2.3
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: [ "-js" ]

  wasmcloud-a:
    image: wasmcloud/wasmcloud_host:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "4000:4000"
    environment:
      - HOST_HOSTNAME=wasmcloud-a
      - WASMCLOUD_PROV_RPC_HOST=nats
      - WASMCLOUD_RPC_HOST=nats
      - WASMCLOUD_CTL_HOST=nats
      - RUST_LOG=trace
      - RUST_BACKTRACE=1
      - WASMCLOUD_CLUSTER_SEED=SCAHM2E4GQBDYNAHKYYKYFMKAGWF2EWTUIEJN47LGPGLASACOFRS3EWP7Y
  
  wasmcloud-b:
    image: wasmcloud/wasmcloud_host:latest
    environment:
      - HOST_HOSTNAME=wasmcloud-b
      - WASMCLOUD_PROV_RPC_HOST=nats
      - WASMCLOUD_RPC_HOST=nats
      - WASMCLOUD_CTL_HOST=nats 
      - RUST_LOG=trace
      - RUST_BACKTRACE=1
      - WASMCLOUD_CLUSTER_SEED=SCAHM2E4GQBDYNAHKYYKYFMKAGWF2EWTUIEJN47LGPGLASACOFRS3EWP7Y
```
</details>
<details>
<summary>and a script like this:</summary>

```bash
#!/bin/bash
set -euxo pipefail

cd $(dirname $0)

docker-compose stop
docker-compose up -d --remove-orphans

until [[ $(wash ctl get hosts -o json | jq -r .hosts[].id | wc -l) == $(grep '^  wasmcloud-[a-z]:$' docker-compose.yml | wc -l) ]]; do
    sleep 1
done

wash ctl start provider \
    wasmcloud.azurecr.io/httpserver:0.14.4 \
    --timeout 20 \
    --constraint hostname=wasmcloud-a

wash ctl start actor \
    wasmcloud.azurecr.io/echo:0.3.2 \
    --timeout 20 \
    --constraint hostname=wasmcloud-b

wash ctl link put \
    MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5 \
    VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M \
    wasmcloud:httpserver \
    ADDRESS=0.0.0.0:8081

# host_ids=$(wash ctl get hosts -o json | jq -r .hosts[].id)
# for id in $host_ids; do
#     wash ctl get inventory $id -o json | jq
# done

until [[ $(curl -v --fail localhost:8081/thingies) != '' ]]; do
    echo "waiting for http server to start working"
    sleep 1
done

docker-compose stop wasmcloud-b

while curl -v --fail localhost:8081/thingies; do
    echo "curl should fail when we stop the actor"
    sleep 1
done

docker-compose stop wasmcloud-a

docker-compose stop
```
</details>

## Enhancement Proposal

The log line feels like there is some validation happening somewhere. Is there any way to store this information anywhere so that it can be queried later, and surfaced in washboard/wash ctl?

Some options:

a) My initial thought was that you could reject `wash ctl link put` if validation errors occur, but the validation happens in the capability provider, which might not even be running yet, so this probably won't work.

b) Store the status on the link object (a bit like how you put a status field on kubernetes pods). If the link definition fails validation then you write an entry into the status log for the link saying so. When the link is validated by each actor/provider on each host, it adds an entry to the log.

c) Store a status log on the HTTP capability provider, in a way that is queryable by washboard and `wash ctl get inventory ... -o json`

d) Write a logging capability provider that has a ring buffer of logs at each level of severity, and then have a way to query by capability-provider-id + severity. You could then surface anything of severity ERROR and higher in washboard (as an expandable warnings counter in the the http provider row?).

e) Something I've not thought of.
