### ISSUE TITLE
Error in wash repl when trying to start the provider v0.2.3

### ISSUE THREAD

**Issue by emonidi** [wasmCloud/capability-providers#72]
I run wash in ubuntu:latest container and when I open wash with "wash up" and type: 

`ctl start provider wasmcloud.azurecr.io/httpclient:0.2.3  `

i get the following error: 

`ERROR:wasmcloud_host::capability::native_host:/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmcloud-host-0.18.0/src/capability/native_host.rs:100:Failed to extract plugin from provider: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

**Comment by brooksmtownsend** [comment]
Hey @emonidi, this looks like a missing shared object in your Linux installation. Do you have `libssl-dev` installed?

Here's a list of ubuntu dependencies you might want to verify are installed on your image:
```
build-essential
pkg-config
libssl-dev
llvm
clang
```

I've installed these via `apt` in the past, but you may need to use `snap` now that ubuntu is pushing it instead.

**Comment by autodidaddict** [comment]
For context, `libloading` can often fail with a "no such file or directory" if it's attempting to load one of the dependencies like libC, libssl, etc.

**Comment by emonidi** [comment]
Hey guys I wasnt hoping for such a fast answer. :D Thank you about that. I will try to follow your advice @brooksmtownsend and come back to you when I succeed/fail. 
Thanks again for the support.

**Comment by emonidi** [comment]
> Hey @emonidi, this looks like a missing shared object in your Linux installation. Do you have `libssl-dev` installed?
> 
> Here's a list of ubuntu dependencies you might want to verify are installed on your image:
> 
> ```
> build-essential
> pkg-config
> libssl-dev
> llvm
> clang
> ```
> 
> I've installed these via `apt` in the past, but you may need to use `snap` now that ubuntu is pushing it instead.

@brooksmtownsend after installing all of the packages you recomended I also get the same error unfortunatelly. I can see that you labeled the issue as a bug. Is this a problem of the httpclient provider or something that I am doing wrong?

**Comment by brooksmtownsend** [comment]
@emonidi Strange 🤔 Would you mind linking the Dockerfile for the image that you're using? I'm assuming you're using docker, so the equivalent configuration file would work in your environment 🙂 

I've labeled this as a bug because you're running into this issue, once we figure out the real problem I may shuffle the labels around but this helps us track the issue for now

**Comment by emonidi** [comment]
I must say that I am very new to docker and most likely I am doing something wrong. I appreciate your support.

Dockerfile: 

```
FROM ubuntu:latest

RUN apt-get update && apt-get install -y
RUN apt-get -qq -y install curl wget libssl1.0 libssl-dev llvm clang
RUN curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | bash
RUN apt -qq -y install wasmcloud wash

EXPOSE "6222:6222"
EXPOSE "4222:4222"
EXPOSE "8222:8222"
```

docker-compose.yml:

```
# also available at https://github.com/wasmCloud/wash/blob/main/tools/docker-compose.yml
version: "3"
services:
  registry:
    image: registry:2
    ports:
     - "5000:5000"
  nats:
    image: nats:2.1.9
    ports:
      - "6222:6222"
      - "4222:4222"
      - "8222:8222"
  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"

```
